/**
 * @fileoverview gRPC-Web generated client stub for data
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: data.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as data_pb from './data_pb';


export class DataClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorTweetStream = new grpcWeb.MethodDescriptor(
    '/data.Data/TweetStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    data_pb.TweetStreamRequest,
    data_pb.Bird,
    (request: data_pb.TweetStreamRequest) => {
      return request.serializeBinary();
    },
    data_pb.Bird.deserializeBinary
  );

  tweetStream(
    request: data_pb.TweetStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<data_pb.Bird> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/data.Data/TweetStream',
      request,
      metadata || {},
      this.methodDescriptorTweetStream);
  }

  methodDescriptorGetBird = new grpcWeb.MethodDescriptor(
    '/data.Data/GetBird',
    grpcWeb.MethodType.UNARY,
    data_pb.BirdRequest,
    data_pb.Bird,
    (request: data_pb.BirdRequest) => {
      return request.serializeBinary();
    },
    data_pb.Bird.deserializeBinary
  );

  getBird(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null): Promise<data_pb.Bird>;

  getBird(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: data_pb.Bird) => void): grpcWeb.ClientReadableStream<data_pb.Bird>;

  getBird(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: data_pb.Bird) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/data.Data/GetBird',
        request,
        metadata || {},
        this.methodDescriptorGetBird,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/data.Data/GetBird',
    request,
    metadata || {},
    this.methodDescriptorGetBird);
  }

  methodDescriptorGetAllBirds = new grpcWeb.MethodDescriptor(
    '/data.Data/GetAllBirds',
    grpcWeb.MethodType.UNARY,
    data_pb.BirdsRequest,
    data_pb.Birds,
    (request: data_pb.BirdsRequest) => {
      return request.serializeBinary();
    },
    data_pb.Birds.deserializeBinary
  );

  getAllBirds(
    request: data_pb.BirdsRequest,
    metadata: grpcWeb.Metadata | null): Promise<data_pb.Birds>;

  getAllBirds(
    request: data_pb.BirdsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: data_pb.Birds) => void): grpcWeb.ClientReadableStream<data_pb.Birds>;

  getAllBirds(
    request: data_pb.BirdsRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: data_pb.Birds) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/data.Data/GetAllBirds',
        request,
        metadata || {},
        this.methodDescriptorGetAllBirds,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/data.Data/GetAllBirds',
    request,
    metadata || {},
    this.methodDescriptorGetAllBirds);
  }

  methodDescriptorGetBirdTweets = new grpcWeb.MethodDescriptor(
    '/data.Data/GetBirdTweets',
    grpcWeb.MethodType.UNARY,
    data_pb.BirdRequest,
    data_pb.Tweets,
    (request: data_pb.BirdRequest) => {
      return request.serializeBinary();
    },
    data_pb.Tweets.deserializeBinary
  );

  getBirdTweets(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null): Promise<data_pb.Tweets>;

  getBirdTweets(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: data_pb.Tweets) => void): grpcWeb.ClientReadableStream<data_pb.Tweets>;

  getBirdTweets(
    request: data_pb.BirdRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: data_pb.Tweets) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/data.Data/GetBirdTweets',
        request,
        metadata || {},
        this.methodDescriptorGetBirdTweets,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/data.Data/GetBirdTweets',
    request,
    metadata || {},
    this.methodDescriptorGetBirdTweets);
  }

}

